/** Renders a stored (or freshly derived) glyph SVG. Monochrome: inherits currentColor. */
export function Glyph({ svg, className }: { svg: string; className?: string }) {
  return (
    <div
      className={className}
      // The SVG is generated by @bindle/core's pure glyph() from a content
      // hash — no user-controlled markup passes through here.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
